vich_uploader:
    db_driver: orm

    mappings:
        pictures:
            uri_prefix: /media/pictures
            upload_destination: '%kernel.project_dir%/public/media/pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
